### ISSUE TITLE
Maintaining orderbook

### ISSUE THREAD

**Issue by badokun** [ColossusFX/Ftx.Client.Websocket#1]
Thanks for your excellent work in implementing the websocket api. Do you have any plans on maintaining the orderbook, once the snapshot has been returned. Seems that logic would reside outside of your client api, but very useful to have an active/accurate view on the state of the orderbook. 

Keeping the orderbook up to date, would involve taking the snapshot, and then on each OrderBookUpdateStream update, adjust the orderbook accordingly. 

Didn't see this in the example app

**Comment by ColossusFX** [comment]
Hi,

think you are looking for this

https://github.com/ColossusFX/crypto-websocket-extensions

**Comment by badokun** [comment]
Exactly what I was looking for, thanks!
